name: KHC
favicon: null
layout_spectrum: 0.6755748286377639
typography_spectrum: 0.8437705950345844
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3109424428548664
  lightness: 0.8289054555352777
  saturation: 0.6348341638222337
  rhythmicContrast: 0.41868542903102934
purpose: []
